site_name: 我的个人主页
site_description: 一个用 Python MkDocs 搭建的个人站点
site_author: 你的名字
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - toc.integrate
plugins:
  - search
nav:
  - 首页: index.md
  - 关于我: about.md
  - 博客:
      - 博客首页: blog/index.md
      - 第一篇文章: blog/hello-world.md
extra:
  social:
    - icon: material/github
      link: https://github.com/yourname
    - icon: material/email
      link: mailto:you@example.com