site_name: 我的个人主页
site_description: 一个用 Python MkDocs 搭建的个人站点
site_author: xuerong Wang
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - toc.integrate
plugins:
  - search
nav:
  - 首页: index.md
  - 关于我: about.md
  - 博客:
      - 博客首页: blog/index.md

markdown_extensions:
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xuerong2024

extra_css:
  - stylesheets/extra.css
